######################################################################
# Automatically generated by qmake (3.0) Fri Sep 26 12:48:03 2014
######################################################################

TEMPLATE = app
TARGET = age_calc
INCLUDEPATH += .

# Input
HEADERS += inputform.h
SOURCES += age_calc.cpp inputform.cpp

# Widgets and QDataStream
QT += core widgets

# derp
CONFIG += c++11
